replicaCount: 5

image:
  repository: teamparallax/parallax-beginner-k8s-workshop
  tag: 2.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

peristence:
  storage: 5Mi

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod-public

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http

application:
  trainee: Marcel
