apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-workshop
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: k8s-workshop
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: sqllite-vol
              mountPath: /data/
          env:
            - name: TRAINEE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: TRAINEE
            - name: SQLLITE_FILEPATH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: SQLLITE_FILEPATH
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sqllite-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
