postgresql:
  persistence:
    size: 2Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: staging.example.wiki.workshop.team-parallax.com
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
#    - secretName: wiki-example-tls
#      hosts:
#        - example.wiki.workshop.team-parallax.com